
/**************************************************************
 *	
 *	eye, 8 bit, 11025Hz,
 *	1 channel, 2403552 bytes/channel
 *	Total Size: 1 * 2403552 + 4 (header) = 2403596 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Chianne/Desktop/CS2261/ChianneConnelly_FinalProj2/eye.wav
 *	Time-stamp: Tue Dec 05 18:16:25 2017
 *	
 **************************************************************/

#ifndef __EYEH__
#define __EYEH__

#define EYEFREQ 11025
#define EYELEN 2403552

extern const unsigned char eye[2403552];

#endif /* __EYEH__ */
