
/**************************************************************
 *	
 *	gameSong, 8 bit, 11025Hz,
 *	1 channel, 88200 bytes/channel
 *	Total Size: 1 * 88200 + 4 (header) = 88244 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Chianne/Desktop/CS2261/ChianneConnelly_FinalProj2/gameSong.wav
 *	Time-stamp: Wed Nov 29 14:29:12 2017
 *	
 **************************************************************/

#ifndef __GAMESONGH__
#define __GAMESONGH__

#define GAMESONGFREQ 11025
#define GAMESONGLEN 88200

extern const unsigned char gameSong[88200];

#endif /* __GAMESONGH__ */
