
/**************************************************************
 *	
 *	ice, 8 bit, 11025Hz,
 *	1 channel, 25472 bytes/channel
 *	Total Size: 1 * 25472 + 4 (header) = 25516 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Chianne/Desktop/CS2261/ChianneConnelly_FinalProj2/ice.wav
 *	Time-stamp: Mon Nov 27 16:35:35 2017
 *	
 **************************************************************/

#ifndef __ICEH__
#define __ICEH__

#define ICEFREQ 11025
#define ICELEN 25472

extern const unsigned char ice[25472];

#endif /* __ICEH__ */
