
/**************************************************************
 *	
 *	loseSound, 8 bit, 11025Hz,
 *	1 channel, 44029 bytes/channel
 *	Total Size: 1 * 44029 + 4 (header) = 44073 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Chianne/Desktop/CS2261/ChianneConnelly_FinalProj2/loseSound.wav
 *	Time-stamp: Tue Dec 05 19:16:18 2017
 *	
 **************************************************************/

#ifndef __LOSESOUNDH__
#define __LOSESOUNDH__

#define LOSESOUNDFREQ 11025
#define LOSESOUNDLEN 44029

extern const unsigned char loseSound[44029];

#endif /* __LOSESOUNDH__ */
