
/**************************************************************
 *	
 *	scream, 8 bit, 11025Hz,
 *	1 channel, 56049 bytes/channel
 *	Total Size: 1 * 56049 + 4 (header) = 56093 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Chianne/Desktop/CS2261/ChianneConnelly_FinalProj2/scream.wav
 *	Time-stamp: Mon Nov 27 20:27:50 2017
 *	
 **************************************************************/

#ifndef __SCREAMH__
#define __SCREAMH__

#define SCREAMFREQ 11025
#define SCREAMLEN 56049

extern const unsigned char scream[56049];

#endif /* __SCREAMH__ */
