
/**************************************************************
 *	
 *	StartSFX, 8 bit, 11025Hz,
 *	1 channel, 127584 bytes/channel
 *	Total Size: 1 * 127584 + 4 (header) = 127628 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Chianne/Desktop/CS2261/Labs/Lab11/StartSFX.wav
 *	Time-stamp: Mon Nov 20 17:11:39 2017
 *	
 **************************************************************/

#ifndef __STARTSFXH__
#define __STARTSFXH__

#define STARTSFXFREQ 11025
#define STARTSFXLEN 127584

extern const unsigned char StartSFX[127584];

#endif /* __STARTSFXH__ */
