
/**************************************************************
 *	
 *	winSong, 8 bit, 11025Hz,
 *	1 channel, 79488 bytes/channel
 *	Total Size: 1 * 79488 + 4 (header) = 79532 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Chianne/Desktop/CS2261/ChianneConnelly_FinalProj2/winSong.wav
 *	Time-stamp: Tue Dec 05 17:43:40 2017
 *	
 **************************************************************/

#ifndef __WINSONGH__
#define __WINSONGH__

#define WINSONGFREQ 11025
#define WINSONGLEN 79488

extern const unsigned char winSong[79488];

#endif /* __WINSONGH__ */
